<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\WeatherForecastController.cs" />
    <Compile Remove="WeatherForecast.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Navira.Shop.Application\Navira.Shop.Application.csproj" />
    <ProjectReference Include="..\Navira.Shop.Core.Services\Navira.Shop.Core.Services.csproj" />
    <ProjectReference Include="..\Navira.Shop.Core.Web\Navira.Shop.Core.Web.csproj" />
    <ProjectReference Include="..\Navira.Shop.Infrastructure\Navira.Shop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
